// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClipboardContainsFilePaths() {
  return window['go']['backend']['App']['ClipboardContainsFilePaths']();
}

export function CopyFilePathsToClipboard(arg1) {
  return window['go']['backend']['App']['CopyFilePathsToClipboard'](arg1);
}

export function CopyFiles(arg1, arg2) {
  return window['go']['backend']['App']['CopyFiles'](arg1, arg2);
}

export function CreateDirectory(arg1, arg2) {
  return window['go']['backend']['App']['CreateDirectory'](arg1, arg2);
}

export function DeleteFiles(arg1) {
  return window['go']['backend']['App']['DeleteFiles'](arg1);
}

export function DeletePath(arg1) {
  return window['go']['backend']['App']['DeletePath'](arg1);
}

export function ExecuteCommand(arg1, arg2) {
  return window['go']['backend']['App']['ExecuteCommand'](arg1, arg2);
}

export function FileExists(arg1) {
  return window['go']['backend']['App']['FileExists'](arg1);
}

export function FormatFileSize(arg1) {
  return window['go']['backend']['App']['FormatFileSize'](arg1);
}

export function GetAvailableTerminals() {
  return window['go']['backend']['App']['GetAvailableTerminals']();
}

export function GetCurrentWorkingDirectory() {
  return window['go']['backend']['App']['GetCurrentWorkingDirectory']();
}

export function GetDriveInfo() {
  return window['go']['backend']['App']['GetDriveInfo']();
}

export function GetFileDetails(arg1) {
  return window['go']['backend']['App']['GetFileDetails'](arg1);
}

export function GetHomeDirectory() {
  return window['go']['backend']['App']['GetHomeDirectory']();
}

export function GetQuickAccessPaths() {
  return window['go']['backend']['App']['GetQuickAccessPaths']();
}

export function GetSystemRoots() {
  return window['go']['backend']['App']['GetSystemRoots']();
}

export function HealthCheck() {
  return window['go']['backend']['App']['HealthCheck']();
}

export function HideFiles(arg1) {
  return window['go']['backend']['App']['HideFiles'](arg1);
}

export function IsHidden(arg1) {
  return window['go']['backend']['App']['IsHidden'](arg1);
}

export function ListDirectory(arg1) {
  return window['go']['backend']['App']['ListDirectory'](arg1);
}

export function MoveFiles(arg1, arg2) {
  return window['go']['backend']['App']['MoveFiles'](arg1, arg2);
}

export function MoveFilesToRecycleBin(arg1) {
  return window['go']['backend']['App']['MoveFilesToRecycleBin'](arg1);
}

export function NavigateToPath(arg1) {
  return window['go']['backend']['App']['NavigateToPath'](arg1);
}

export function OpenFile(arg1) {
  return window['go']['backend']['App']['OpenFile'](arg1);
}

export function OpenInSystemExplorer(arg1) {
  return window['go']['backend']['App']['OpenInSystemExplorer'](arg1);
}

export function OpenPowerShellHere(arg1) {
  return window['go']['backend']['App']['OpenPowerShellHere'](arg1);
}

export function OpenTerminalHere(arg1) {
  return window['go']['backend']['App']['OpenTerminalHere'](arg1);
}

export function RenameFile(arg1, arg2) {
  return window['go']['backend']['App']['RenameFile'](arg1, arg2);
}

export function StreamDirectory(arg1) {
  return window['go']['backend']['App']['StreamDirectory'](arg1);
}

export function ValidatePath(arg1) {
  return window['go']['backend']['App']['ValidatePath'](arg1);
}
