// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function CopyFiles(arg1:Array<string>,arg2:string):Promise<boolean>;

export function CreateDirectory(arg1:string,arg2:string):Promise<backend.NavigationResponse>;

export function DeleteFiles(arg1:Array<string>):Promise<boolean>;

export function DeletePath(arg1:string):Promise<backend.NavigationResponse>;

export function ExecuteCommand(arg1:string,arg2:string):Promise<boolean>;

export function FileExists(arg1:string):Promise<boolean>;

export function FormatFileSize(arg1:number):Promise<string>;

export function GetAvailableTerminals():Promise<Array<string>>;

export function GetCurrentWorkingDirectory():Promise<string>;

export function GetDriveInfo():Promise<Array<Record<string, any>>>;

export function GetFileDetails(arg1:string):Promise<backend.FileInfo>;

export function GetHomeDirectory():Promise<string>;

export function GetQuickAccessPaths():Promise<Array<Record<string, any>>>;

export function GetSystemRoots():Promise<Array<string>>;

export function HealthCheck():Promise<Record<string, any>>;

export function HideFiles(arg1:Array<string>):Promise<boolean>;

export function IsHidden(arg1:string):Promise<boolean>;

export function ListDirectory(arg1:string):Promise<backend.NavigationResponse>;

export function MoveFiles(arg1:Array<string>,arg2:string):Promise<boolean>;

export function MoveFilesToRecycleBin(arg1:Array<string>):Promise<boolean>;

export function NavigateToPath(arg1:string):Promise<backend.NavigationResponse>;

export function NavigateUp(arg1:string):Promise<backend.NavigationResponse>;

export function OpenFile(arg1:string):Promise<boolean>;

export function OpenInSystemExplorer(arg1:string):Promise<boolean>;

export function OpenPowerShellHere(arg1:string):Promise<boolean>;

export function OpenTerminalHere(arg1:string):Promise<boolean>;

export function RenameFile(arg1:string,arg2:string):Promise<boolean>;

export function ValidatePath(arg1:string):Promise<boolean>;
