// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CopyFiles(arg1, arg2) {
  return window['go']['main']['App']['CopyFiles'](arg1, arg2);
}

export function CreateDirectory(arg1, arg2) {
  return window['go']['main']['App']['CreateDirectory'](arg1, arg2);
}

export function DeleteFiles(arg1) {
  return window['go']['main']['App']['DeleteFiles'](arg1);
}

export function DeletePath(arg1) {
  return window['go']['main']['App']['DeletePath'](arg1);
}

export function FormatFileSize(arg1) {
  return window['go']['main']['App']['FormatFileSize'](arg1);
}

export function GetCurrentWorkingDirectory() {
  return window['go']['main']['App']['GetCurrentWorkingDirectory']();
}

export function GetDriveInfo() {
  return window['go']['main']['App']['GetDriveInfo']();
}

export function GetFileDetails(arg1) {
  return window['go']['main']['App']['GetFileDetails'](arg1);
}

export function GetHomeDirectory() {
  return window['go']['main']['App']['GetHomeDirectory']();
}

export function GetSystemRoots() {
  return window['go']['main']['App']['GetSystemRoots']();
}

export function ListDirectory(arg1) {
  return window['go']['main']['App']['ListDirectory'](arg1);
}

export function MoveFiles(arg1, arg2) {
  return window['go']['main']['App']['MoveFiles'](arg1, arg2);
}

export function MoveFilesToRecycleBin(arg1) {
  return window['go']['main']['App']['MoveFilesToRecycleBin'](arg1);
}

export function NavigateToPath(arg1) {
  return window['go']['main']['App']['NavigateToPath'](arg1);
}

export function NavigateUp(arg1) {
  return window['go']['main']['App']['NavigateUp'](arg1);
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function OpenInSystemExplorer(arg1) {
  return window['go']['main']['App']['OpenInSystemExplorer'](arg1);
}
