// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateDirectory(arg1:string,arg2:string):Promise<main.NavigationResponse>;

export function DeletePath(arg1:string):Promise<main.NavigationResponse>;

export function FormatFileSize(arg1:number):Promise<string>;

export function GetCurrentWorkingDirectory():Promise<string>;

export function GetDriveInfo():Promise<Array<Record<string, any>>>;

export function GetFileDetails(arg1:string):Promise<main.FileInfo>;

export function GetHomeDirectory():Promise<string>;

export function GetSystemRoots():Promise<Array<string>>;

export function ListDirectory(arg1:string):Promise<main.NavigationResponse>;

export function NavigateToPath(arg1:string):Promise<main.NavigationResponse>;

export function NavigateUp(arg1:string):Promise<main.NavigationResponse>;

export function OpenInSystemExplorer(arg1:string):Promise<boolean>;
